baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Tickets"
theme = "tickets"
enableRobotsTXT = true

[params]
  description = "Test."
  subTitle = "Test"
  socialImage = "images/jacobproffer-social.jpg"
