baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Tickets"
theme = "tickets"
enableRobotsTXT = true

[params]
  description = "A collection of movie tickets purchased by Jacob Proffer."
  images = ["images/jacobproffer-social.jpg"]
