baseURL = "https://tickets.proffer.dev/"
languageCode = "en-us"
title = "Dead Man's Brew"
theme = "tickets"
paginate = 14
enableRobotsTXT = true

[taxonomies]
  theater = "theaters"
  rating = "ratings"


[params]
  description = "The ongoing movie ticket collection of Jacob Proffer, started in 2007."
  images = ["images/tickets-social.jpg"]
  subTitle = "A Movie Ticket Collection"
