baseURL = "https://tickets.proffer.dev/"
languageCode = "en-us"
title = "Dead Man's Brew"
theme = "tickets"
enableRobotsTXT = true

[params]
  description = "The ongoing movie ticket collection of Jacob Proffer, started in 2007."
  images = ["images/tickets-social.jpg"]
  subTitle = "A Movie Ticket Collection"
