baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Tickets"
theme = "tickets"
googleAnalytics = "UA-57480521-1"
enableRobotsTXT = true
summaryLength = 14
paginate = 110

[params]
  description = "Test."
  socialImage = "images/jacobproffer-social.jpg"
