baseURL = "https://jacobproffer.com/"
languageCode = "en-us"
title = "Dead Man's Brew"
theme = "tickets"
enableRobotsTXT = true

[params]
  description = "A collection of movie tickets purchased by Jacob Proffer."
  images = ["images/tickets-social.jpg"]
  subTitle = "A Movie Ticket Collection"
