name = "Tickets"
license = "Apache 2.0"
licenselink = "https://github.com/jacobproffer/blog/blob/master/LICENSE"
description = "Source code for Jacob Proffer's ticket project."
homepage = "https://jacobproffer.com/"
tags = ["blog"]
features = ["blog", "posts"]
min_version = "0.41"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev/"
