name = "Tickets"
license = "Apache 2.0"
licenselink = "https://github.com/jacobproffer/tickets/blob/master/LICENSE"
description = "Source code for Jacob Proffer's ticket project."
homepage = "https://jacobproffer.com/"
tags = ["collection", "tickets", "grid"]
features = ["data", "grid"]
min_version = "0.132.1"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev/"
